services:
  db:
    image: postgres
    container_name: db-test-postgres
    networks:
      - app-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

networks:
  app-network:
    name: devcontainer-nextjs-network
